import { PRODUCT_NAME, RETAILERS } from "@pricetruth/shared";

const retailerNames = Object.values(RETAILERS)
  .map((r) => r.displayName)
  .join(" or ");

export const COPY = {
  tagline: "Know what it really costs.",
  today: "TODAY",
  storeSays: "STORE SAYS",
  historySays: "HISTORY SAYS",
  noAdvertisedDiscount: "No advertised discount",
  storeReference: (pct: number, ref: string) => `${pct}% off store reference of ${ref}`,
  typicalRecentPrice: "Typical recent price",
  belowTypical: (pct: number) => `~${pct}% below typical recent price`,
  aboveTypical: (pct: number) => `~${pct}% above typical recent price`,
  typical30: "30-day typical",
  typical90: "90-day typical",
  typical180: "180-day typical",
  low90: "90-day low",
  recordedLow: `${PRODUCT_NAME} recorded low`,
  notEnoughData: "Not enough data",
  discountIntegrity: "Discount Integrity",
  dealScore: "Deal Score",
  why: "Why?",
  confidence: "Confidence",
  confidenceLabel: (level: string) => level.charAt(0) + level.slice(1).toLowerCase(),
  observationsAcross: (count: number, days: number) => `${count} observations across ${days} days`,
  idle: `Open a supported product page on ${retailerNames}.`,
  unsupported: "This page isn't a supported product page.",
  noPrice: "We couldn't read a price on this page, so nothing was recorded.",
  ambiguous:
    "We found this product but could not confidently determine its current price. Nothing was recorded.",
  loading: "Reading price evidence…",
  retry: "Retry",
  learningTitle: "Still learning this listing",
  learningBody: `${PRODUCT_NAME} needs more price history before Deal Score and Discount Integrity are ready. Today's price is shown; scores appear once coverage improves.`,
  learningObserved: (count: number) =>
    count === 1 ? "1 observation so far" : `${count} observations so far`,
  learningFirstSeen: (when: string) => `First observed ${when}`,
  historyHeading: "Price history",
  historyChartLabel: "Price history chart",
  historyTableSummary: "View price history as a table",
  historyDay: "Day",
  historyMedian: "Median price",
  chartWindowGroup: "History window",
  chartWindows: {
    d30: "30D",
    d90: "90D",
    d180: "180D",
    all: "ALL",
  },
  feedbackPrompt: "Is this price correct?",
  feedbackLooksRight: "Looks right",
  feedbackReport: "Report issue",
  feedbackThanks: "Thanks. Your note stays on this device.",
  feedbackReported: "Issue noted locally. Nothing was sent.",
  diagnostics: "Diagnostics",
  diagnosticsHide: "Hide diagnostics",
  diagnosticsRetailer: "Retailer",
  diagnosticsExternalId: "External ID",
  diagnosticsGeneration: "Generation",
  diagnosticsApiBase: "API base",
  diagnosticsWarnings: "Warnings",
  diagnosticsStatus: "Tab status",
  diagnosticsAdapter: "Adapter version",
  diagnosticsNone: "none",
  statusIdle: "Waiting for a product page",
  statusUnsupported: "Page is not supported",
  statusAmbiguous: "Price is ambiguous; nothing recorded",
  statusLoading: "Loading price analysis",
  statusReady: "Price analysis ready",
  statusReadyInsufficient: "Price shown; scores waiting on more history",
  statusError: "Something went wrong",
} as const;
